"""
Source of truth for every user-facing string. Edit the rows below, then run:

    python tools/gen_strings.py

It rewrites src/Obhijatri.App/Strings/bn-BD/Resources.resw and en-US/Resources.resw with the same keys,
and refuses to write if a key is duplicated or a string contains an em or en dash.
"""
import html, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "Obhijatri.App", "Strings")

rows = [
    # key, Bangla, English
    ("AppTitle", "অভিযাত্রী", "Obhijatri"),
    ("WindowTitleFormat", "{0} - {1}", "{0} - {1}"),
    ("PrivateWindowTitleFormat", "প্রাইভেট: {0}", "Private: {0}"),
    ("PrivateBadge", "প্রাইভেট", "Private"),
    ("TabStripName", "ট্যাব", "Tabs"),
    ("NewTabTitle", "নতুন ট্যাব", "New tab"),
    ("CloseTabTooltip", "ট্যাব বন্ধ করুন (Ctrl+W)", "Close tab (Ctrl+W)"),

    ("BackButtonTooltip", "পেছনে যান (Alt+বাম তীর)", "Back (Alt+Left)"),
    ("ForwardButtonTooltip", "সামনে যান (Alt+ডান তীর)", "Forward (Alt+Right)"),
    ("ReloadButtonTooltip", "রিলোড করুন (F5)", "Reload (F5)"),
    ("StopButtonTooltip", "লোড হওয়া থামান", "Stop loading"),
    ("HomeButtonTooltip", "হোম পেজ (Alt+Home)", "Home page (Alt+Home)"),
    ("DownloadsButtonTooltip", "ডাউনলোড (Ctrl+J)", "Downloads (Ctrl+J)"),
    ("MenuButtonTooltip", "আরও অপশন", "More options"),
    ("AddressBarPlaceholder", "ওয়েবসাইটের ঠিকানা লিখুন বা সার্চ করুন", "Type a web address or search"),
    ("AddressBarName", "অ্যাড্রেস বার", "Address bar"),

    ("MenuNewTab", "নতুন ট্যাব (Ctrl+T)", "New tab (Ctrl+T)"),
    ("MenuNewPrivateWindow", "নতুন প্রাইভেট উইন্ডো (Ctrl+Shift+N)", "New private window (Ctrl+Shift+N)"),
    ("MenuHistory", "হিস্ট্রি (Ctrl+H)", "History (Ctrl+H)"),
    ("MenuDownloads", "ডাউনলোড (Ctrl+J)", "Downloads (Ctrl+J)"),
    ("MenuImportBookmarks", "অন্য ব্রাউজার থেকে বুকমার্ক ইমপোর্ট করুন", "Import bookmarks from another browser"),
    ("MenuShowBookmarkBar", "বুকমার্ক বার দেখান (Ctrl+Shift+B)", "Show bookmark bar (Ctrl+Shift+B)"),
    ("MenuVerticalTabs", "ট্যাব পাশে দেখান", "Show tabs on the side"),

    ("EngineErrorTitle", "ব্রাউজার ইঞ্জিন চালু হয়নি", "The browser engine did not start"),
    ("EngineErrorMessage", "Microsoft WebView2 Runtime ইনস্টল করা আছে কিনা দেখুন, তারপর অভিযাত্রী আবার চালু করুন।", "Check that the Microsoft WebView2 Runtime is installed, then restart Obhijatri."),
    ("PageCrashedTitle", "পেজটি ঠিকমতো চলছে না", "This page stopped working"),
    ("PageCrashedMessage", "রিলোড বাটনে চাপুন।", "Press Reload to try again."),
    ("DatabaseErrorTitle", "হিস্ট্রি ও বুকমার্ক সেভ করা যাচ্ছে না", "History and bookmarks cannot be saved"),
    ("DatabaseErrorMessage", "ডেটা ফাইলটি খোলা যায়নি। এবার যা করবেন তা সেভ হবে না।", "The data file could not be opened. Nothing from this session will be saved."),
    ("DialogCancel", "বাতিল", "Cancel"),
    ("DialogSave", "সেভ করুন", "Save"),

    ("HistoryTitle", "হিস্ট্রি", "History"),
    ("HistorySearchPlaceholder", "হিস্ট্রিতে সার্চ করুন", "Search history"),
    ("HistoryClearButton", "হিস্ট্রি মুছুন", "Clear history"),
    ("HistoryClearHour", "শেষ এক ঘণ্টা", "Last hour"),
    ("HistoryClearDay", "শেষ ২৪ ঘণ্টা", "Last 24 hours"),
    ("HistoryClearAll", "পুরো হিস্ট্রি", "All history"),
    ("HistoryEmpty", "এখনো কোনো হিস্ট্রি নেই।", "No history yet."),
    ("HistoryNoMatches", "কিছু পাওয়া যায়নি।", "Nothing found."),
    ("HistoryDeleteEntry", "হিস্ট্রি থেকে মুছুন", "Remove from history"),
    ("HistoryConfirmTitle", "হিস্ট্রি মুছবেন?", "Clear history?"),
    ("HistoryConfirmHour", "শেষ এক ঘণ্টায় দেখা সব পেজ হিস্ট্রি থেকে মুছে যাবে।", "Pages visited in the last hour will be removed from history."),
    ("HistoryConfirmDay", "শেষ ২৪ ঘণ্টায় দেখা সব পেজ হিস্ট্রি থেকে মুছে যাবে।", "Pages visited in the last 24 hours will be removed from history."),
    ("HistoryConfirmAll", "পুরো হিস্ট্রি মুছে যাবে। এটি আর ফেরানো যাবে না।", "All history will be removed. This cannot be undone."),
    ("HistoryConfirmYes", "মুছে ফেলুন", "Clear"),

    ("DownloadsTitle", "ডাউনলোড", "Downloads"),
    ("DownloadsEmpty", "এখনো কিছু ডাউনলোড হয়নি।", "Nothing downloaded yet."),
    ("DownloadOpen", "খুলুন", "Open"),
    ("DownloadShowInFolder", "ফোল্ডারে দেখান", "Show in folder"),
    ("DownloadCancelButton", "বাতিল করুন", "Cancel"),
    ("DownloadProgressFormat", "{0} / {1}", "{0} of {1}"),
    ("DownloadCompletedFormat", "ডাউনলোড শেষ, {0}", "Done, {0}"),
    ("DownloadCanceled", "বাতিল করা হয়েছে", "Canceled"),
    ("DownloadFailed", "ডাউনলোড ব্যর্থ হয়েছে", "Download failed"),
    ("SizeBytesFormat", "{0} বাইট", "{0} bytes"),
    ("SizeKbFormat", "{0} কেবি", "{0} KB"),
    ("SizeMbFormat", "{0} এমবি", "{0} MB"),
    ("SizeGbFormat", "{0} জিবি", "{0} GB"),
    ("DownloadScanning", "স্ক্যান করা হচ্ছে...", "Scanning..."),
    ("DownloadBlocked", "নিরাপত্তার কারণে ব্লক করা হয়েছে", "Blocked for safety"),
    ("DownloadDeleteBlocked", "মুছে ফেলুন", "Delete"),
    ("DownloadDeleted", "মুছে ফেলা হয়েছে", "Deleted"),

    ("BookmarkBarEmpty", "পছন্দের পেজ এখানে রাখতে অ্যাড্রেস বারের পাশের স্টার (☆) চিহ্নে চাপুন।", "To keep a page here, press the star next to the address bar."),
    ("BookmarkAddTooltip", "এই পেজ বুকমার্ক করুন (Ctrl+D)", "Bookmark this page (Ctrl+D)"),
    ("BookmarkEditTooltip", "বুকমার্ক এডিট করুন (Ctrl+D)", "Edit bookmark (Ctrl+D)"),
    ("BookmarkAddedTitle", "বুকমার্ক যোগ হয়েছে", "Bookmark added"),
    ("BookmarkEditTitle", "বুকমার্ক এডিট করুন", "Edit bookmark"),
    ("BookmarkNameLabel", "নাম", "Name"),
    ("BookmarkFolderLabel", "ফোল্ডার", "Folder"),
    ("BookmarkBarFolderName", "বুকমার্ক বার", "Bookmark bar"),
    ("BookmarkDone", "ঠিক আছে", "Done"),
    ("BookmarkRemove", "সরিয়ে দিন", "Remove"),
    ("BookmarkFolderEmpty", "(খালি)", "(Empty)"),
    ("BookmarkOpenInNewTab", "নতুন ট্যাবে খুলুন", "Open in new tab"),
    ("BookmarkRename", "নাম বদলান", "Rename"),
    ("BookmarkRenameTitle", "নতুন নাম", "New name"),
    ("BookmarkNewFolder", "নতুন ফোল্ডার", "New folder"),
    ("BookmarkNewFolderTitle", "ফোল্ডারের নাম", "Folder name"),
    ("BookmarkDelete", "মুছে ফেলুন", "Delete"),

    ("ImportFolderName", "ইমপোর্ট করা বুকমার্ক", "Imported bookmarks"),
    ("ImportDoneTitle", "বুকমার্ক ইমপোর্ট হয়েছে", "Bookmarks imported"),
    ("ImportDoneMessage", "{0}টি বুকমার্ক বুকমার্ক বারের নতুন ফোল্ডারে রাখা হয়েছে।", "{0} bookmarks were added to a new folder on the bookmark bar."),
    ("ImportSkippedMessage", "নিরাপত্তার জন্য {0}টি লিঙ্ক বাদ দেওয়া হয়েছে।", "{0} links were skipped for safety."),
    ("ImportFailedTitle", "বুকমার্ক ইমপোর্ট করা যায়নি", "Could not import bookmarks"),
    ("ImportTooLarge", "ফাইলটি অনেক বড়।", "The file is too large."),
    ("ImportReadError", "ফাইলটি পড়া যায়নি।", "The file could not be read."),
    ("ImportNothingFound", "এই ফাইলে কোনো বুকমার্ক পাওয়া যায়নি। Chrome বা Edge থেকে HTML ফাইল হিসেবে এক্সপোর্ট করা ফাইলটি বেছে নিন।", "No bookmarks were found in this file. Choose a file exported from Chrome or Edge as HTML."),

    ("TabCountFormat", "{0}টি ট্যাব খোলা", "{0} tabs open"),
    ("MenuSettings", "সেটিংস (Ctrl+,)", "Settings (Ctrl+,)"),
    ("SettingsTitle", "সেটিংস", "Settings"),
    ("ToggleOn", "চালু", "On"),
    ("ToggleOff", "বন্ধ", "Off"),

    ("DateTimeFormat", "{0} {1} {2}, {3}", "{0} {1} {2}, {3}"),
    ("TimeFormat", "{1} {0}", "{0} {1}"),
    ("TimeDawn", "ভোর", "AM"),
    ("TimeMorning", "সকাল", "AM"),
    ("TimeNoon", "দুপুর", "PM"),
    ("TimeAfternoon", "বিকাল", "PM"),
    ("TimeEvening", "সন্ধ্যা", "PM"),
    ("TimeNight", "রাত", "PM"),
    ("TimeAm", "পূর্বাহ্ণ", "AM"),
    ("TimePm", "অপরাহ্ণ", "PM"),
    ("Month1", "জানুয়ারি", "Jan"),
    ("Month2", "ফেব্রুয়ারি", "Feb"),
    ("Month3", "মার্চ", "Mar"),
    ("Month4", "এপ্রিল", "Apr"),
    ("Month5", "মে", "May"),
    ("Month6", "জুন", "Jun"),
    ("Month7", "জুলাই", "Jul"),
    ("Month8", "আগস্ট", "Aug"),
    ("Month9", "সেপ্টেম্বর", "Sep"),
    ("Month10", "অক্টোবর", "Oct"),
    ("Month11", "নভেম্বর", "Nov"),
    ("Month12", "ডিসেম্বর", "Dec"),

    ("SettingsGeneral", "প্রধান সেটিংস", "General"),
    ("SettingsSecurity", "নিরাপত্তা", "Security"),
    ("SettingsPrivacy", "প্রাইভেসি", "Privacy"),
    ("SettingsAppearance", "থিম", "Appearance"),
    ("SettingsAdvanced", "অ্যাডভান্সড", "Advanced"),

    ("SettingsLanguage", "ভাষা", "Language"),
    ("SettingsLanguageDescription", "মেনু, বাটন আর মেসেজ কোন ভাষায় দেখাবে।", "The language of menus, buttons and messages."),
    ("LanguageBangla", "বাংলা", "বাংলা"),
    ("LanguageEnglish", "English", "English"),
    ("SettingsLanguageRestartTitle", "রিস্টার্ট করতে হবে", "Restart needed"),
    ("SettingsLanguageRestartMessage", "নতুন ভাষা দেখতে অভিযাত্রী রিস্টার্ট করুন। খোলা ট্যাবগুলো আবার ফিরে আসবে।", "Restart Obhijatri to see the new language. Your open tabs will come back."),
    ("SettingsRestartNow", "এখনই রিস্টার্ট করুন", "Restart now"),
    ("SettingsHomePage", "হোম পেজ", "Home page"),
    ("SettingsHomePageDescription", "নতুন ট্যাবে আর হোম বাটনে চাপলে এই পেজটি খুলবে।", "This page opens in new tabs and when you press Home."),
    ("SettingsHomePageSaved", "সেভ হয়েছে।", "Saved."),
    ("SettingsHomePageInvalid", "এটি সঠিক ওয়েবসাইটের ঠিকানা নয়। যেমন: prothomalo.com", "This is not a valid web address. For example: prothomalo.com"),
    ("SettingsSearchEngine", "সার্চ ইঞ্জিন", "Search engine"),
    ("SettingsSearchEngineDescription", "অ্যাড্রেস বারে কিছু লিখে সার্চ করলে কোথায় খোঁজা হবে।", "Where words typed in the address bar are searched."),
    ("SearchEngineGoogle", "Google", "Google"),
    ("SearchEngineBing", "Bing", "Bing"),
    ("SearchEngineDuckDuckGo", "DuckDuckGo", "DuckDuckGo"),
    ("SettingsRestoreTabs", "আগের ট্যাবগুলো আবার খুলুন", "Reopen previous tabs"),
    ("SettingsRestoreTabsDescription", "অভিযাত্রী চালু হলে গতবারের খোলা ট্যাবগুলো ফিরে আসবে।", "When Obhijatri starts, the tabs from last time come back."),

    ("SettingsSmartScreen", "Microsoft Defender SmartScreen", "Microsoft Defender SmartScreen"),
    ("SettingsSmartScreenDescription", "ক্ষতিকর ওয়েবসাইট আর ডাউনলোড সম্পর্কে সতর্ক করে। চালু রাখাই ভালো।", "Warns about harmful sites and downloads. Keeping it on is recommended."),
    ("SettingsPopups", "পপ-আপ ব্লক", "Pop-up blocking"),
    ("SettingsPopupsDescription", "আপনি নিজে ক্লিক না করলে কোনো সাইট নতুন উইন্ডো বা ট্যাব খুলতে পারে না। এটি সবসময় চালু থাকে।", "Sites cannot open new windows or tabs unless you clicked. This is always on."),
    ("SettingsSafeSchemes", "নিরাপদ ঠিকানা", "Safe addresses"),
    ("SettingsSafeSchemesDescription", "কোনো ওয়েবসাইট আপনার কম্পিউটারের ফাইল বা অন্য প্রোগ্রাম খুলতে পারে না। এটি সবসময় চালু থাকে।", "Web pages cannot open files or other programs on your computer. This is always on."),

    ("SettingsTracking", "ট্র্যাকিং প্রোটেকশন", "Tracking protection"),
    ("SettingsTrackingDescription", "যারা এক সাইট থেকে আরেক সাইটে আপনাকে ট্র্যাক করে, তাদের আটকায়।", "Blocks trackers that follow you from site to site."),
    ("SettingsTrackingBasic", "বেসিক: বেশিরভাগ ট্র্যাকার চলবে, সব সাইট ঠিকমতো কাজ করবে", "Basic: most trackers allowed, all sites work"),
    ("SettingsTrackingBalanced", "ব্যালান্সড: অচেনা সাইটের ট্র্যাকার আটকাবে", "Balanced: blocks trackers from sites you have not visited"),
    ("SettingsTrackingStrict", "স্ট্রিক্ট: প্রায় সব ট্র্যাকার আটকাবে (এটাই ভালো), কোনো সাইট ঠিকমতো না চললে ব্যালান্সড বেছে নিন", "Strict: blocks most trackers (recommended); choose Balanced if a site does not work"),
    ("SettingsClearSiteData", "কুকি ও সাইটের ডেটা", "Cookies and site data"),
    ("SettingsClearSiteDataDescription", "সব সাইট থেকে লগ আউট হয়ে যাবেন এবং ক্যাশ ফাইল মুছে যাবে।", "You will be signed out of all sites and cached files will be removed."),
    ("SettingsClearSiteDataButton", "কুকি ও সাইটের ডেটা মুছুন", "Clear cookies and site data"),
    ("SettingsClearSiteDataConfirmTitle", "কুকি ও সাইটের ডেটা মুছবেন?", "Clear cookies and site data?"),
    ("SettingsClearSiteDataConfirmMessage", "সব সাইট থেকে লগ আউট হয়ে যাবেন। এটি আর ফেরানো যাবে না।", "You will be signed out of all sites. This cannot be undone."),
    ("SettingsClearSiteDataDone", "মুছে ফেলা হয়েছে।", "Cleared."),
    ("SettingsClearSiteDataNothing", "এখনো কোনো ওয়েবসাইট খোলা হয়নি, তাই মোছার কিছু নেই।", "No web page has been opened yet, so there is nothing to clear."),
    ("SettingsHistory", "হিস্ট্রি", "History"),
    ("SettingsHistoryDescription", "কোন কোন পেজ দেখেছেন তার তালিকা দেখুন বা মুছুন। প্রাইভেট উইন্ডোর পেজ কখনো হিস্ট্রিতে থাকে না।", "See or clear the list of pages you visited. Private window pages are never kept."),
    ("SettingsOpenHistory", "হিস্ট্রি খুলুন", "Open history"),

    ("SettingsTheme", "লাইট ও ডার্ক মোড", "Theme"),
    ("SettingsThemeDescription", "অভিযাত্রী আর ওয়েবসাইট লাইট না ডার্ক মোডে দেখাবে।", "Whether Obhijatri and web pages use light or dark colours."),
    ("SettingsThemeSystem", "Windows-এর মতো", "Same as Windows"),
    ("SettingsThemeLight", "লাইট", "Light"),
    ("SettingsThemeDark", "ডার্ক", "Dark"),
    ("SettingsBookmarkBar", "বুকমার্ক বার দেখান", "Show bookmark bar"),
    ("SettingsBookmarkBarDescription", "অ্যাড্রেস বারের নিচে পছন্দের পেজগুলো দেখাবে।", "Shows your favourite pages under the address bar."),
    ("SettingsVerticalTabs", "ট্যাব পাশে দেখান", "Show tabs on the side"),
    ("SettingsVerticalTabsDescription", "অনেক ট্যাব খোলা থাকলে পাশে লম্বা লিস্টে নাম পড়া সহজ হয়।", "With many tabs open, a list on the side is easier to read."),
    ("SettingsFont", "বাংলা ফন্ট", "Bangla font"),
    ("SettingsFontDescription", "অভিযাত্রীর মেনু আর বাটনে Hind Siliguri ফন্ট ব্যবহার হয়, যা অ্যাপের সঙ্গেই আছে।", "Obhijatri's menus and buttons use the bundled Hind Siliguri font."),

    ("SettingsDataFolder", "ডেটা ফোল্ডার", "Data folder"),
    ("SettingsDataFolderDescription", "হিস্ট্রি, বুকমার্ক আর সেটিংস শুধু এই কম্পিউটারের এই ফোল্ডারে থাকে। কোথাও পাঠানো হয় না।", "History, bookmarks and settings are kept only in this folder on this computer. Nothing is sent anywhere."),
    ("SettingsOpenDataFolder", "ফোল্ডার খুলুন", "Open folder"),
    ("SettingsVersion", "ভার্সন", "Version"),

    ("PhoneticButtonOn", "অ", "অ"),
    ("PhoneticButtonOff", "A", "A"),
    ("PhoneticAddressOn", "অ্যাড্রেস বারে বাংলা টাইপিং চালু। বন্ধ করতে চাপুন (Ctrl+M)", "Bangla typing in the address bar is on. Press to turn off (Ctrl+M)"),
    ("PhoneticAddressOff", "অ্যাড্রেস বারে বাংলা টাইপিং বন্ধ। চালু করতে চাপুন (Ctrl+M)", "Bangla typing in the address bar is off. Press to turn on (Ctrl+M)"),
    ("PhoneticPageOn", "বাংলা টাইপিং চালু। বন্ধ করতে চাপুন (Ctrl+M)", "Bangla typing is on. Press to turn off (Ctrl+M)"),
    ("PhoneticPageOff", "বাংলা টাইপিং বন্ধ। চালু করতে চাপুন (Ctrl+M)", "Bangla typing is off. Press to turn on (Ctrl+M)"),
    ("PhoneticSuggestionsName", "বাংলা শব্দের সাজেশন", "Bangla word suggestions"),
    ("SettingsTyping", "বাংলা টাইপিং", "Bangla typing"),
    ("SettingsTypingDescription", "ইংরেজি অক্ষরে লিখলেই বাংলা হবে, যেমন ami লিখলে আমি। যেকোনো লেখার ঘরে Ctrl+M চাপুন, বা ঘরের পাশের অ/A বাটনে চাপুন। প্রতিটি ওয়েবসাইটের জন্য আলাদা করে মনে রাখা হয়। পাসওয়ার্ডের ঘরে কখনো চালু হয় না।", "Type Bangla with English letters, for example ami becomes আমি. In any text box press Ctrl+M, or the অ/A button next to the box. Each website remembers its own choice. It never works in password boxes."),
    ("SettingsTypingAddressBar", "অ্যাড্রেস বারে বাংলা টাইপিং", "Bangla typing in the address bar"),
    ("SettingsTypingAddressBarDescription", "চালু থাকলে অ্যাড্রেস বারে লেখা বাংলা হবে। ওয়েবসাইটের ঠিকানা লেখার সময় বন্ধ রাখুন।", "When on, text typed in the address bar becomes Bangla. Keep it off while typing a website address."),

    ("ShieldTooltip", "বিজ্ঞাপন ব্লক ও নিরাপত্তা", "Ad blocking and security"),
    ("ShieldSecure", "এই সাইটের সাথে সংযোগ নিরাপদ (HTTPS)।", "Your connection to this site is secure (HTTPS)."),
    ("ShieldNotSecure", "এই সাইটের সাথে সংযোগ নিরাপদ নয়। পাসওয়ার্ড বা কার্ডের তথ্য দেবেন না।", "Your connection to this site is not secure. Do not enter passwords or card details."),
    ("ShieldBlockedFormat", "এই পেজে {0}টি বিজ্ঞাপন ও ট্র্যাকার ব্লক করা হয়েছে।", "{0} ads and trackers were blocked on this page."),
    ("ShieldBlockingOff", "বিজ্ঞাপন ব্লক বন্ধ আছে। সেটিংসের প্রাইভেসি অংশ থেকে চালু করুন।", "Ad blocking is off. Turn it on in the Privacy section of Settings."),
    ("ShieldAllowAdsFormat", "{0} সাইটে বিজ্ঞাপন দেখান", "Show ads on {0}"),
    ("ShieldAllowAdsHint", "যে সাইট বিজ্ঞাপনের টাকায় চলে, তাকে সাহায্য করতে চাইলে চালু করুন। পেজটি রিলোড হবে।", "Turn on to support a site that is paid for by ads. The page will reload."),
    ("HttpsWarningTitle", "নিরাপদ সংযোগ নেই", "No secure connection"),
    ("HttpsWarningHeading", "এই সাইটটি নিরাপদ সংযোগ (HTTPS) দেয় না", "This site does not offer a secure connection (HTTPS)"),
    ("HttpsWarningBody", "এই সাইটে আপনি যা দেখবেন বা লিখবেন, মাঝপথে অন্য কেউ তা দেখতে বা বদলে দিতে পারে। যেমন একই ওয়াইফাইতে থাকা কেউ।", "Anything you see or type on this site could be read or changed on the way, for example by someone on the same Wi-Fi."),
    ("HttpsWarningAdvice", "পাসওয়ার্ড, পিন, ওটিপি বা কার্ডের তথ্য কখনো এমন সাইটে দেবেন না।", "Never enter a password, PIN, OTP or card details on a site like this."),
    ("HttpsWarningProceed", "ঝুঁকি বুঝেছি, তবুও চালিয়ে যান", "I understand the risk, continue anyway"),
    ("InterstitialBack", "নিরাপদ জায়গায় ফিরে যান", "Go back to safety"),
    ("SettingsHttpsOnly", "শুধু নিরাপদ সংযোগ (HTTPS)", "Secure connections only (HTTPS)"),
    ("SettingsHttpsOnlyDescription", "সাইট সবসময় নিরাপদ সংযোগে খোলা হবে। কোনো সাইট নিরাপদ সংযোগ না দিলে আগে সতর্ক করা হবে।", "Sites always open over a secure connection. If a site does not offer one, you are warned first."),
    ("SettingsBlockAds", "বিজ্ঞাপন ও ট্র্যাকার ব্লক", "Block ads and trackers"),
    ("SettingsBlockAdsDescription", "বিজ্ঞাপন আর আপনাকে অনুসরণকারী ট্র্যাকার আটকায়, তাই পেজ তাড়াতাড়ি খোলে আর ডেটা কম খরচ হয়। প্রতিটি সাইটের জন্য আলাদা করে বন্ধ করা যায়।", "Blocks ads and trackers that follow you, so pages open faster and use less data. Can be turned off for each site."),
    ("SettingsFilterLists", "ব্লক লিস্ট", "Block lists"),
    ("SettingsFilterListsDescription", "EasyList ও EasyPrivacy লিস্ট, সপ্তাহে একবার নিজে থেকেই আপডেট হয়। শুধু লিস্টটি ডাউনলোড হয়, আপনার কোনো তথ্য পাঠানো হয় না।", "EasyList and EasyPrivacy, updated automatically once a week. Only the lists are downloaded; nothing about you is sent."),
    ("SettingsFilterStatusFormat", "{0}টি নিয়ম। শেষ আপডেট: {1}", "{0} rules. Last updated: {1}"),
    ("SettingsFilterBundled", "অ্যাপের সঙ্গে দেওয়া লিস্ট", "the lists that came with the app"),
    ("SettingsFilterUpdateNow", "এখনই আপডেট করুন", "Update now"),
    ("SettingsFilterUpdated", "লিস্ট আপডেট হয়েছে।", "Lists updated."),
    ("SettingsFilterUpdateFailed", "আপডেট করা যায়নি। ইন্টারনেট সংযোগ দেখে আবার চেষ্টা করুন।", "Could not update. Check the internet connection and try again."),

    ("ScamWarningTitle", "সতর্কতা: ভুয়া হতে পারে", "Warning: this may be fake"),
    ("ScamWarningHeadingLookalikeFormat", "এই ঠিকানাটি {0}-এর মতো দেখতে, কিন্তু আসল সাইট নয়", "This address looks like {0}, but it is not the real site"),
    ("ScamWarningBodyLookalikeFormat", "আসল ঠিকানা হলো {0}। প্রতারকরা একই রকম দেখতে ঠিকানা বানিয়ে পাসওয়ার্ড, ওটিপি বা পিন চুরি করে।", "The real address is {0}. Scammers make look-alike addresses like this to steal passwords, OTPs or PINs."),
    ("ScamWarningHeadingKnownScam", "এই ঠিকানাটি পরিচিত একটি স্ক্যাম সাইট হিসেবে চিহ্নিত", "This address is on a list of known scam sites"),
    ("ScamWarningBodyKnownScam", "এই সাইট নিয়ে আগে অন্যদের কাছ থেকে প্রতারণার খবর পাওয়া গেছে।", "This site has been reported by others as a scam before."),
    ("ScamWarningHeadingSafeBrowsing", "এই ঠিকানাটি ঝুঁকিপূর্ণ হিসেবে চিহ্নিত", "This address is flagged as risky"),
    ("ScamWarningBodySafeBrowsing", "গুগল সেফ ব্রাউজিং এই ঠিকানাটিকে ক্ষতিকর বা প্রতারণামূলক বলে চিহ্নিত করেছে।", "Google Safe Browsing has flagged this address as harmful or deceptive."),
    ("ScamWarningAdvice", "পাসওয়ার্ড, পিন, ওটিপি বা কার্ডের তথ্য দেবেন না। সন্দেহ হলে সরাসরি অফিসিয়াল অ্যাপ বা নম্বরে যোগাযোগ করুন।", "Do not enter a password, PIN, OTP or card details. If in doubt, contact the official app or number directly."),
    ("ScamWarningProceed", "আমি ঝুঁকি বুঝেছি, তবুও চালিয়ে যান", "I understand the risk, continue anyway"),

    ("BrandBkash", "বিকাশ", "bKash"),
    ("BrandNagad", "নগদ", "Nagad"),
    ("BrandRocket", "রকেট", "Rocket"),
    ("BrandDutchBangla", "ডাচ-বাংলা ব্যাংক", "Dutch-Bangla Bank"),
    ("BrandSonaliBank", "সোনালী ব্যাংক", "Sonali Bank"),
    ("BrandAgraniBank", "অগ্রণী ব্যাংক", "Agrani Bank"),
    ("BrandJanataBank", "জনতা ব্যাংক", "Janata Bank"),
    ("BrandRupaliBank", "রূপালী ব্যাংক", "Rupali Bank"),
    ("BrandIslamiBank", "ইসলামী ব্যাংক বাংলাদেশ", "Islami Bank Bangladesh"),
    ("BrandBracBank", "ব্র্যাক ব্যাংক", "BRAC Bank"),
    ("BrandCityBank", "দ্য সিটি ব্যাংক", "The City Bank"),
    ("BrandEbl", "ইস্টার্ন ব্যাংক (EBL)", "Eastern Bank (EBL)"),
    ("BrandBangladeshBank", "বাংলাদেশ ব্যাংক", "Bangladesh Bank"),
    ("BrandNid", "জাতীয় পরিচয়পত্র (NID)", "National ID (NID)"),
    ("BrandPassport", "ই-পাসপোর্ট", "e-Passport"),
    ("BrandGovBd", "বাংলাদেশ সরকারের ওয়েবসাইট", "the Bangladesh government website"),
    ("BrandBrta", "বিআরটিএ (BRTA)", "BRTA"),
    ("BrandGrameenphone", "গ্রামীণফোন", "Grameenphone"),
    ("BrandRobi", "রবি", "Robi"),
    ("BrandBanglalink", "বাংলালিংক", "Banglalink"),
    ("BrandDaraz", "দারাজ", "Daraz"),
    ("BrandFacebook", "ফেসবুক", "Facebook"),
    ("BrandWhatsapp", "হোয়াটসঅ্যাপ", "WhatsApp"),
    ("BrandInstagram", "ইনস্টাগ্রাম", "Instagram"),
    ("BrandGoogle", "গুগল", "Google"),
    ("BrandMicrosoft", "মাইক্রোসফট", "Microsoft"),
    ("BrandApple", "অ্যাপল", "Apple"),
    ("BrandAmazon", "অ্যামাজন", "Amazon"),
    ("BrandPaypal", "পেপাল", "PayPal"),
    ("BrandNetflix", "নেটফ্লিক্স", "Netflix"),

    ("SettingsScamShield", "স্ক্যাম ও ভুয়া ওয়েবসাইট সতর্কতা", "Scam and fake website warnings"),
    ("SettingsScamShieldDescription", "বিকাশ, নগদ, ব্যাংক বা ফেসবুকের মতো সাইটের নকল ঠিকানা এবং পরিচিত স্ক্যাম সাইট দেখলে পুরো পেজ জুড়ে সতর্ক করা হয়।", "Warns with a full-page message for look-alike addresses of sites like bKash, Nagad, a bank or Facebook, and known scam sites."),
    ("SettingsScamListStatusFormat", "তালিকায় {0}টি ঠিকানা। {1}", "{0} addresses on the list. {1}"),

    ("DialogOk", "ঠিক আছে", "OK"),
    ("PasswordLeakWarningTitle", "এই পাসওয়ার্ডটি আগে ফাঁস হয়েছে", "This password has been leaked before"),
    ("PasswordLeakWarningMessageFormat", "এই পাসওয়ার্ডটি অন্তত {0}টি ডেটা ফাঁসে পাওয়া গেছে, তাই এটি অনুমান করা সহজ। এখানে বা অন্য কোথাও ব্যবহার করলে পাসওয়ার্ডটি বদলে ফেলুন।", "This password has shown up in at least {0} known data breaches, so it is easy to guess. If you use it here or anywhere else, change it."),
    ("SettingsPasswordLeakCheck", "ফাঁস হওয়া পাসওয়ার্ড সতর্কতা", "Leaked password warning"),
    ("SettingsPasswordLeakCheckDescription", "লগইন ফর্মে পাসওয়ার্ড দেওয়ার সময়, তা আগে কোনো ডেটা ফাঁসে পাওয়া গেছে কিনা যাচাই করা হয়। পাসওয়ার্ডটি নিজে কখনো পাঠানো হয় না, শুধু এর হ্যাশের প্রথম কয়েকটি অক্ষর।", "When a password is entered on a login form, checks whether it has appeared in a known data breach before. The password itself is never sent, only the first few characters of its hash."),

    ("PermissionPromptTitleFormat", "{0} অনুমতি চাইছে", "{0} is asking for permission"),
    ("PermissionPromptCamera", "এই সাইটকে কি আপনার ক্যামেরা ব্যবহার করতে দেবেন?", "Let this site use your camera?"),
    ("PermissionPromptMicrophone", "এই সাইটকে কি আপনার মাইক্রোফোন ব্যবহার করতে দেবেন?", "Let this site use your microphone?"),
    ("PermissionPromptLocation", "এই সাইটকে কি আপনার লোকেশন দেখতে দেবেন?", "Let this site see your location?"),
    ("PermissionAllow", "অনুমতি দিন", "Allow"),
    ("PermissionDeny", "দেবেন না", "Deny"),
    ("PermissionNotificationChipTooltip", "নোটিফিকেশন অনুমতির অনুরোধ", "Notification permission request"),
    ("PermissionNotificationChipMessageFormat", "{0} আপনাকে নোটিফিকেশন পাঠাতে চেয়েছিল। ডিফল্টভাবে বন্ধ রাখা হয়েছে।", "{0} asked to send you notifications. It was turned off by default."),
    ("PermissionNotificationChipHint", "চালু করলে পরের বার এই সাইটে নোটিফিকেশন দেখাবে।", "Turning it on will show notifications from this site from now on."),

    ("SettingsPermissions", "সাইটের অনুমতি", "Site permissions"),
    ("SettingsPermissionsDescription", "যেসব সাইটকে ক্যামেরা, মাইক্রোফোন, লোকেশন বা নোটিফিকেশনের অনুমতি দেওয়া বা বন্ধ করা হয়েছে, তার তালিকা।", "Sites that were allowed or denied camera, microphone, location or notification access."),
    ("SettingsPermissionsEmpty", "এখনো কোনো সাইটকে বিশেষ অনুমতি দেওয়া বা বন্ধ করা হয়নি।", "No site has been given or denied a special permission yet."),
    ("SettingsPermissionsRevoke", "মুছে ফেলুন (আবার জিজ্ঞাসা করবে)", "Remove (will ask again)"),
    ("PermissionKindCamera", "ক্যামেরা", "Camera"),
    ("PermissionKindMicrophone", "মাইক্রোফোন", "Microphone"),
    ("PermissionKindLocation", "লোকেশন", "Location"),
    ("PermissionKindNotifications", "নোটিফিকেশন", "Notifications"),
    ("PermissionStateAllowed", "অনুমতি দেওয়া", "Allowed"),
    ("PermissionStateDenied", "বন্ধ", "Denied"),

    ("ClipboardGuardTitle", "ক্লিপবোর্ডে কিছু কপি হয়েছে", "Something was copied to the clipboard"),
    ("ClipboardGuardMessageFormat", "{0} আপনার ক্লিপবোর্ডে কিছু লিখেছে, যদিও আপনি কপি করেননি। কোথাও পেস্ট করার আগে দেখে নিন।", "{0} wrote to your clipboard, although you did not copy anything. Check before pasting it anywhere."),
    ("SettingsClipboardGuard", "ক্লিপবোর্ড গার্ড", "Clipboard guard"),
    ("SettingsClipboardGuardDescription", "কোনো সাইট নিজে থেকে (আপনার কপি করা ছাড়া) ক্লিপবোর্ডে কিছু লিখলে সতর্ক করা হয়।", "Warns when a site writes to the clipboard on its own, without you copying anything."),

    ("PaymentLockBadge", "নিরাপদ মোড", "Safe mode"),
    ("PaymentLockTooltip", "ব্যাংক বা পেমেন্ট সাইট: তৃতীয় পক্ষের স্ক্রিপ্ট ব্লক করা হয়েছে", "Bank or payment site: third-party scripts are blocked"),
    ("SettingsPaymentLock", "পেমেন্ট লক মোড", "Payment lock mode"),
    ("SettingsPaymentLockDescription", "বিকাশ, নগদ, ব্যাংক বা পেপালের মতো সাইটে তৃতীয় পক্ষের স্ক্রিপ্ট ব্লক করা হয় এবং টুলবারে সবুজ নিরাপদ মোড ব্যাজ দেখানো হয়।", "On sites like bKash, Nagad, a bank or PayPal, third-party scripts are blocked and a green safe mode badge shows in the toolbar."),

    ("SettingsCookieAutoDelete", "কুকি অটো-ডিলিট", "Cookie auto-delete"),
    ("SettingsCookieAutoDeleteDescription", "চালু থাকলে, বুকমার্ক করা নেই এমন সাইটের কুকি অভিযাত্রী বন্ধ করার সময় মুছে যাবে।", "When on, cookies for sites that are not bookmarked are deleted when Obhijatri closes."),

    ("PinTab", "ট্যাব পিন করুন", "Pin tab"),
    ("UnpinTab", "ট্যাব আনপিন করুন", "Unpin tab"),
    ("TabSleepingTip", "স্লিপে আছে, ক্লিক করলে আবার চালু হবে", "Sleeping, click to wake it"),
    ("TabMemoryFormat", "মেমরি: {0}", "Memory: {0}"),
    ("RamMeterTooltip", "মেমরি ব্যবহার", "Memory use"),
    ("RamTitle", "মেমরি ব্যবহার", "Memory use"),
    ("RamTotalFormat", "মোট: {0}", "Total: {0}"),
    ("RamShellFormat", "অভিযাত্রীর নিজের অংশ: {0}", "Obhijatri itself: {0}"),
    ("RamEngineFormat", "ওয়েব পেজ ও ইঞ্জিন: {0}", "Web pages and engine: {0}"),
    ("RamSleepingFormat", "{0}টি ট্যাব স্লিপে আছে", "{0} tabs are asleep"),
    ("RamSavedTodayFormat", "আজ বাঁচানো মেমরি: {0}", "Memory saved today: {0}"),
    ("RamSleepNow", "ব্যাকগ্রাউন্ড ট্যাব এখনই স্লিপে পাঠান", "Sleep background tabs now"),
    ("RamHint", "স্লিপে যাওয়ার আগে ও পরে ট্যাবের মেমরির পার্থক্য যোগ করে আজকের হিসাব করা হয়। গান বা ভিডিও চলা ও পিন করা ট্যাব স্লিপে যায় না।", "Today's figure adds up how much less memory each tab used after it went to sleep. Tabs playing sound or video, and pinned tabs, never sleep."),
    ("SettingsTabSleep", "ট্যাব স্লিপ", "Tab sleep"),
    ("SettingsTabSleepDescription", "কিছুক্ষণ ব্যবহার না করলে ব্যাকগ্রাউন্ড ট্যাব থামিয়ে মেমরি বাঁচানো হয়। ট্যাবে ক্লিক করলেই আবার চালু হয়। গান বা ভিডিও চলা ও পিন করা ট্যাব স্লিপে যায় না।", "Background tabs you have not used for a while are paused to save memory. Click a tab to wake it. Tabs playing sound or video, and pinned tabs, never sleep."),
    ("SettingsTabSleepOff", "বন্ধ", "Off"),
    ("SettingsTabSleepMinutesFormat", "{0} মিনিট পর", "After {0} minutes"),
    ("SettingsMemoryMeter", "মেমরি মিটার", "Memory meter"),
    ("SettingsMemoryMeterDescription", "টুলবারে অভিযাত্রী মোট কতটুকু মেমরি ব্যবহার করছে তা দেখায়।", "Shows in the toolbar how much memory Obhijatri is using in total."),
    ("MenuLowData", "লো-ডেটা মোড", "Low data mode"),
    ("SettingsLowData", "লো-ডেটা মোড", "Low data mode"),
    ("SettingsLowDataDescription", "মোবাইল হটস্পটে ডেটা বাঁচাতে: ভিডিও অটোপ্লে বন্ধ, ইউটিউব বা ফেসবুক প্লাগইনের মতো ভারী এমবেড ব্লক করা হয় এবং পেজ খোলার পরে যোগ হওয়া ছবি স্ক্রল করলে লোড হয়। পেজ রিলোড করলে বদল কাজ করে।", "To save data on a mobile hotspot: video autoplay is off, heavy embeds such as YouTube or Facebook plugins are blocked, and images added after a page opens load only as you scroll. The change applies when a page is reloaded."),
    ("BanglaMonth1", "বৈশাখ", "Boishakh"),
    ("BanglaMonth2", "জ্যৈষ্ঠ", "Joishtho"),
    ("BanglaMonth3", "আষাঢ়", "Asharh"),
    ("BanglaMonth4", "শ্রাবণ", "Srabon"),
    ("BanglaMonth5", "ভাদ্র", "Bhadro"),
    ("BanglaMonth6", "আশ্বিন", "Ashwin"),
    ("BanglaMonth7", "কার্তিক", "Kartik"),
    ("BanglaMonth8", "অগ্রহায়ণ", "Ogrohayon"),
    ("BanglaMonth9", "পৌষ", "Poush"),
    ("BanglaMonth10", "মাঘ", "Magh"),
    ("BanglaMonth11", "ফাল্গুন", "Falgun"),
    ("BanglaMonth12", "চৈত্র", "Choitro"),
    ("BanglaSeason1", "গ্রীষ্মকাল", "Summer"),
    ("BanglaSeason2", "বর্ষাকাল", "Monsoon"),
    ("BanglaSeason3", "শরৎকাল", "Autumn"),
    ("BanglaSeason4", "হেমন্তকাল", "Late autumn"),
    ("BanglaSeason5", "শীতকাল", "Winter"),
    ("BanglaSeason6", "বসন্তকাল", "Spring"),
    ("HijriMonth1", "মুহাররম", "Muharram"),
    ("HijriMonth2", "সফর", "Safar"),
    ("HijriMonth3", "রবিউল আউয়াল", "Rabi al-Awwal"),
    ("HijriMonth4", "রবিউস সানি", "Rabi al-Thani"),
    ("HijriMonth5", "জমাদিউল আউয়াল", "Jumada al-Awwal"),
    ("HijriMonth6", "জমাদিউস সানি", "Jumada al-Thani"),
    ("HijriMonth7", "রজব", "Rajab"),
    ("HijriMonth8", "শা'বান", "Shaban"),
    ("HijriMonth9", "রমজান", "Ramadan"),
    ("HijriMonth10", "শাওয়াল", "Shawwal"),
    ("HijriMonth11", "জিলকদ", "Dhul Qadah"),
    ("HijriMonth12", "জিলহজ", "Dhul Hijjah"),
    ("Weekday0", "রবিবার", "Sunday"),
    ("Weekday1", "সোমবার", "Monday"),
    ("Weekday2", "মঙ্গলবার", "Tuesday"),
    ("Weekday3", "বুধবার", "Wednesday"),
    ("Weekday4", "বৃহস্পতিবার", "Thursday"),
    ("Weekday5", "শুক্রবার", "Friday"),
    ("Weekday6", "শনিবার", "Saturday"),
    ("NewTabDateBangla", "বাংলা", "Bangla"),
    ("NewTabDateEnglish", "ইংরেজি", "English"),
    ("NewTabDateHijri", "হিজরি (সৌদি ক্যালেন্ডার)", "Hijri (Saudi calendar)"),
    ("NewTabBanglaDateFormat", "{0} {1} {2} বঙ্গাব্দ", "{0} {1} {2} BS"),
    ("NewTabBanglaDateSeasonFormat", "{0}, {1}", "{0}, {1}"),
    ("NewTabGregorianDateFormat", "{0}, {1} {2} {3}", "{0}, {1} {2} {3}"),
    ("NewTabHijriDateFormat", "{0} {1} {2} হিজরি", "{0} {1} {2} AH"),
    ("NewTabPrayerTitle", "নামাজের সময়", "Prayer times"),
    ("NewTabPrayerDistrict", "জেলা", "District"),
    ("NewTabPrayerNextFormat", "পরের ওয়াক্ত: {0}, {1}", "Next: {0}, {1}"),
    ("NewTabHijriNote", "হিজরি তারিখ সৌদি আরবের ক্যালেন্ডার অনুযায়ী, বাংলাদেশের তারিখ থেকে আলাদা হতে পারে। ঈদ ও রমজানের জন্য সরকারি ক্যালেন্ডার ও ছুটির তালিকা দেখুন।", "The Hijri date follows Saudi Arabia's calendar and can differ from Bangladesh's. For Eid and Ramadan, use the government calendar and holiday list."),
    ("NewTabPrayerNote", "সময় এই কম্পিউটারেই হিসাব করা হয়, ইন্টারনেট লাগে না। ইসলামিক ফাউন্ডেশনের মতো করাচি পদ্ধতি (ফজর ও এশা ১৮ ডিগ্রি) ও হানাফি আসর ধরা হয়েছে, তবে সরকারি সময়সূচি ইসলামিক ফাউন্ডেশনের, তাই দুই সময়ের মধ্যে পার্থক্য থাকলে ফাউন্ডেশনের সময়সূচি মানুন।", "Times are worked out on this computer, no internet needed. They use the Karachi method (Fajr and Isha at 18 degrees) and Hanafi Asr, as the Islamic Foundation does, but the official timetable is the Islamic Foundation's, so if the two differ, follow the Foundation."),
    ("PrayerFajr", "ফজর", "Fajr"),
    ("PrayerSunrise", "সূর্যোদয়", "Sunrise"),
    ("PrayerDhuhr", "জোহর", "Dhuhr"),
    ("PrayerAsr", "আসর", "Asr"),
    ("PrayerMaghrib", "মাগরিব", "Maghrib"),
    ("PrayerIsha", "এশা", "Isha"),
    ("NewTabTopSites", "প্রায়ই দেখা সাইট", "Frequently visited"),
    ("SpeedDialProthomAlo", "প্রথম আলো", "Prothom Alo"),
    ("SpeedDialBkash", "বিকাশ", "bKash"),
    ("SpeedDialDaraz", "দারাজ", "Daraz"),
    ("SpeedDialFacebook", "ফেসবুক", "Facebook"),
    ("SpeedDialWikipedia", "উইকিপিডিয়া", "Wikipedia"),
    ("SpeedDialDailyStar", "ডেইলি স্টার", "The Daily Star"),
    ("SpeedDialBdnews24", "বিডিনিউজ২৪", "bdnews24"),
    ("SpeedDialGoogle", "গুগল", "Google"),
    ("SettingsHijriAdjust", "হিজরি তারিখ", "Hijri date"),
    ("SettingsHijriAdjustDescription", "এই তারিখ সৌদি আরবের ক্যালেন্ডার থেকে নেওয়া, বাংলাদেশ এই ক্যালেন্ডার অনুসরণ করে না। ঈদ ও রমজানের জন্য সরকারি ক্যালেন্ডার ও ছুটির তালিকা দেখুন। চাইলে এখানে দিন কমিয়ে বা বাড়িয়ে নিতে পারেন।", "This date comes from the Saudi Arabian calendar, which Bangladesh does not follow. For Eid and Ramadan, use the government calendar and holiday list. You can shift the day here if you like."),
    ("SettingsHijriSame", "সৌদি আরবের সমান", "Same as Saudi Arabia"),
    ("SettingsHijriBackFormat", "{0} দিন পিছিয়ে", "{0} day(s) earlier"),
    ("SettingsHijriAheadFormat", "{0} দিন এগিয়ে", "{0} day(s) later"),
    ("SettingsFixBanglaFonts", "ওয়েবসাইটে বাংলা ফন্ট ঠিক করুন", "Fix Bangla fonts on websites"),
    ("SettingsFixBanglaFontsDescription", "কিছু সাইটের নিজস্ব ফন্টে বাংলা ভাঙা বা এলোমেলো দেখায়। চালু করলে ওয়েবসাইটের শুধু বাংলা লেখা আপনার কম্পিউটারের ভালো বাংলা ফন্টে (নির্মলা ইউআই) দেখানো হয়; ইংরেজি লেখা ও আইকনের কিছু বদলায় না। পেজ রিলোড করলে বদল কাজ করে।", "Some sites show broken Bangla in their own font. When on, only the Bangla text of websites is drawn in a good Bangla font from your computer (Nirmala UI); English text and icons stay as they are. The change applies when a page is reloaded."),
    ("ReaderButtonTooltip", "রিডার মোড: শুধু লেখা, বড় হরফে", "Reader mode: just the text, in large type"),
    ("ReaderClose", "রিডার বন্ধ করুন", "Close reader"),
    ("ReaderPlay", "পড়ে শোনান", "Read aloud"),
    ("ReaderPause", "থামান", "Pause"),
    ("ReaderStop", "বন্ধ", "Stop"),
    ("ReaderSmaller", "লেখা ছোট করুন", "Smaller text"),
    ("ReaderLarger", "লেখা বড় করুন", "Larger text"),
    ("ReaderTapHint", "কোনো অনুচ্ছেদে ক্লিক করলে সেখান থেকে পড়া শুরু হবে।", "Click a paragraph to start reading from there."),
    ("ReaderUnavailableTitle", "এই পেজে পড়ার মতো লেখা পাওয়া যায়নি", "No article text found on this page"),
    ("ReaderUnavailableMessage", "রিডার মোড খবর বা প্রবন্ধের মতো পেজে কাজ করে।", "Reader mode works on pages like news stories and articles."),
    ("ReaderNoVoiceTitle", "বাংলা ভয়েস ইনস্টল করা নেই", "No Bangla voice is installed"),
    ("ReaderNoVoiceMessage", "পড়ে শোনানোর জন্য Windows-এর বাংলা ভয়েস লাগবে। Windows সেটিংস খুলে সময় ও ভাষা, তারপর স্পিচ, তারপর ভয়েস যোগ করুন থেকে বাংলা বেছে নিন। ইনস্টল হলে রিডার আবার খুলুন।", "Reading aloud needs a Windows Bangla voice. Open Windows Settings, then Time and language, then Speech, then Add voices, and choose Bangla. Open reader again once it is installed."),
    ("ReaderOpenSpeechSettings", "Windows স্পিচ সেটিংস খুলুন", "Open Windows speech settings"),
    ("ReaderSpeechFailed", "পড়ে শোনানো যায়নি", "Could not read aloud"),
    ("MenuReader", "রিডার মোড", "Reader mode"),
    ("BijoyChipText", "ইউনিকোডে বদলান", "Convert to Unicode"),
    ("BijoyChipTooltip", "এই পেজের লেখা বিজয় (SutonnyMJ) ফন্টে, যা ওই ফন্ট ছাড়া ভাঙা দেখায়। ক্লিক করে সাধারণ ইউনিকোড বাংলায় বদলান।", "This page's text is in the Bijoy (SutonnyMJ) font and looks broken without it. Click to convert it to ordinary Unicode Bangla."),
    ("BijoyConvertedTitle", "বদলানো হয়েছে", "Converted"),
    ("BijoyConvertedFormat", "{0}টি লেখা ইউনিকোড বাংলায় বদলানো হয়েছে। রিলোড করলে আগের অবস্থায় ফিরবে।", "{0} pieces of text were converted to Unicode Bangla. Reloading the page brings back the original."),
    ("BijoyNothingTitle", "কিছু বদলানো যায়নি", "Nothing was converted"),
    ("BijoyNothingMessage", "এই পেজে বিজয় ফন্টের কোনো লেখা পাওয়া যায়নি।", "No Bijoy font text was found on this page."),
    ("LowDataEmbedBlocked","লো-ডেটা মোডে এই ভিডিও বা উইজেট ব্লক করা হয়েছে", "Blocked in low data mode"),
]

keys = [r[0] for r in rows]
assert len(keys) == len(set(keys)), "duplicate keys"
for r in rows:
    for text in r[1:]:
        assert "\u2014" not in text and "\u2013" not in text, f"dash in {r[0]}"

head = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>
  <resheader name="version"><value>2.0</value></resheader>
  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>
"""
for i, folder in ((1, "bn-BD"), (2, "en-US")):
    body = "".join(
        f'  <data name="{r[0]}" xml:space="preserve"><value>{html.escape(r[i], quote=False)}</value></data>\n'
        for r in rows)
    with open(os.path.join(ROOT, folder, "Resources.resw"), "w", encoding="utf-8", newline="\r\n") as f:
        f.write(head + body + "</root>\n")
print(len(rows), "strings written")
